# Data Source
We used data from the Bureau of Transportation Statistics to find out how many flights by Alaska Airlines go out from Seatac airport each month and where the destination airport is for these flights in 2024.  
Link: https://www.transtats.bts.gov/ontime/departures.aspx

# Dataset
Link: https://docs.google.com/spreadsheets/d/1wbW6lrl366SCeFGsfLKeCr5Oq9XUVi-p6nCiX6krbk0/edit?usp=drive_link

# Refined Dataset for Sankey Diagram
Link: https://drive.google.com/file/d/1PMmcA7UlwL4fzI9kZT7WWSnjj0LAvPBt/view?usp=drive_link

#

# Mount Google Drive

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

# Load Data from Google Drive

In [ ]:
import pandas as pd
as_flights = pd.read_csv('/content/drive/MyDrive/as_flights.csv')

as_flights.head(5)

,Carrier Code,Date (MM/DD/YYYY),Flight Number,Tail Number,Destination Airport,Scheduled elapsed time (Minutes)
0,AS,01/01/2024,2,N519AS,DCA,296
1,AS,01/01/2024,4,N565AS,DCA,304
2,AS,01/01/2024,16,N433AS,JFK,318
3,AS,01/01/2024,22,N903AK,JFK,318
4,AS,01/01/2024,26,N708AL,JFK,321

#

# Data Filtering

## Filtering Destination Airports

The article in the following link was used to choose which destination airports to include in the sankey diagram. The destination airport with the code CLT was included in the top 10 busiest airports in the article but was not present in the dataset so only the top 9 busiest airports were used.

Link: https://airportscouncil.org/press_release/airports-council-releases-2024-north-american-airport-traffic-rankings/

In [ ]:
as_flights = as_flights.loc[as_flights["Destination Airport"].isin(["ATL", "LAX", "DFW", "DEN", "ORD",
                                                       "JFK", "MCO", "LAS", "CLT", "MIA"])]
as_flights

,Carrier Code,Date (MM/DD/YYYY),Flight Number,Tail Number,Destination Airport,Scheduled elapsed time (Minutes)
2,AS,01/01/2024,16,N433AS,JFK,318
3,AS,01/01/2024,22,N903AK,JFK,318
4,AS,01/01/2024,26,N708AL,JFK,321
5,AS,01/01/2024,34,N709AL,JFK,323
32,AS,01/01/2024,305,N953AK,MIA,350
...,...,...,...,...,...,...
78128,AS,12/31/2024,1246,N486AS,LAX,170
78132,AS,12/31/2024,1287,N538AS,LAX,169
78134,AS,12/31/2024,1300,N214AK,LAX,168
78136,AS,12/31/2024,1306,N453AS,LAX,174
78139,AS,12/31/2024,1316,N294AK,LAX,170

#

# Data Manipulation
## Create a Month column & Drop rows with potential NA values

In [ ]:
as_flights["Month"] = as_flights["Date (MM/DD/YYYY)"].str[:2]
as_flights.dropna()

,Carrier Code,Date (MM/DD/YYYY),Flight Number,Tail Number,Destination Airport,Scheduled elapsed time (Minutes),Month
2,AS,01/01/2024,16,N433AS,JFK,318,01
3,AS,01/01/2024,22,N903AK,JFK,318,01
4,AS,01/01/2024,26,N708AL,JFK,321,01
5,AS,01/01/2024,34,N709AL,JFK,323,01
32,AS,01/01/2024,305,N953AK,MIA,350,01
...,...,...,...,...,...,...,...
78128,AS,12/31/2024,1246,N486AS,LAX,170,12
78132,AS,12/31/2024,1287,N538AS,LAX,169,12
78134,AS,12/31/2024,1300,N214AK,LAX,168,12
78136,AS,12/31/2024,1306,N453AS,LAX,174,12
78139,AS,12/31/2024,1316,N294AK,LAX,170,12

#

# Data Analysis

## Number of flights per month in 2024

In [ ]:
as_flights.groupby("Month").describe()

      Flight Number                                                      \
              count        mean         std   min    25%    50%     75%
Month
01           1078.0  650.888683  354.657001  16.0  372.0  604.0   764.0
02           1013.0  649.728529  356.906115  16.0  372.0  604.0   798.0
03           1215.0  632.242798  370.429195  16.0  366.0  600.0   738.0
04           1241.0  626.762288  369.063093  16.0  366.0  586.0   738.0
05           1371.0  627.769511  364.323969  16.0  372.0  586.0   738.0
06           1452.0  636.405647  360.831227  16.0  376.0  599.0   738.0
07           1529.0  645.311315  360.274908  16.0  394.0  599.0   738.0
08           1512.0  641.030423  361.230721  16.0  376.0  599.0   738.0
09           1434.0  638.394700  365.489973  16.0  372.0  586.0   798.0
10           1300.0  615.434615  355.779907  16.0  372.0  542.0   738.0
11           1188.0  632.367845  375.495003  16.0  366.0  586.0   798.0
12           1275.0  650.288627  384.160372  16.0  366.0  586.0  1005.0

              Scheduled elapsed time (Minutes)                                \
          max                            count        mean        std    min
Month
01     1316.0                           1078.0  216.288497  69.356287  145.0
02     1316.0                           1013.0  216.084896  67.989309  145.0
03     1325.0                           1215.0  220.287243  68.761680  148.0
04     1325.0                           1241.0  222.324738  69.447300  148.0
05     1316.0                           1371.0  222.519329  68.838742  147.0
06     1459.0                           1452.0  219.854683  65.453791  147.0
07     1459.0                           1529.0  218.204055  63.215488  150.0
08     1459.0                           1512.0  218.302910  64.219528  149.0
09     1316.0                           1434.0  218.322873  65.400657  149.0
10     1468.0                           1300.0  214.191538  65.010092  145.0
11     1468.0                           1188.0  218.798822  67.181097  144.0
12     1468.0                           1275.0  221.167059  68.578201  144.0


         25%    50%    75%    max
Month
01     158.0  169.0  279.0  355.0
02     159.0  169.0  281.0  355.0
03     162.0  170.0  284.0  364.0
04     164.0  170.0  288.0  364.0
05     164.0  227.0  290.0  364.0
06     164.0  198.5  255.0  364.0
07     164.0  173.0  246.0  348.0
08     163.0  171.0  250.0  355.0
09     163.0  170.0  251.0  355.0
10     160.0  169.0  249.0  348.0
11     161.0  173.0  275.0  347.0
12     162.0  174.0  284.5  359.0

## Number of flights to each destination airport for each month

In [ ]:
as_flights.groupby(["Destination Airport", "Month"]).describe()

                          Flight Number                                        \
                                  count        mean         std    min    25%
Destination Airport Month
ATL                 01             67.0  410.238806   77.192810  334.0  334.0
                    02             58.0  413.000000   79.689969  334.0  334.0
                    03             76.0  396.302632   71.489117  334.0  334.0
                    04             85.0  394.682353   66.751531  334.0  334.0
                    05            109.0  409.963303   65.967995  334.0  334.0
...                                 ...         ...         ...    ...    ...
ORD                 08            199.0  457.175879  152.568462  328.0  352.0
                    09            186.0  495.290323  238.345948  328.0  352.0
                    10            149.0  413.798658   76.613013  328.0  352.0
                    11            126.0  412.634921   75.175166  328.0  352.0
                    12            134.0  413.641791   74.841929  328.0  352.0

                                                 \
                             50%    75%     max
Destination Airport Month
ATL                 01     376.0  492.0   492.0
                    02     413.0  492.0   492.0
                    03     362.0  492.0   492.0
                    04     362.0  492.0   492.0
                    05     376.0  492.0   492.0
...                          ...    ...     ...
ORD                 08     410.0  538.0  1188.0
                    09     410.0  538.0  1188.0
                    10     408.0  486.0   538.0
                    11     408.0  410.0   538.0
                    12     408.0  410.0   538.0

                          Scheduled elapsed time (Minutes)              \
                                                     count        mean
Destination Airport Month
ATL                 01                                67.0  284.373134
                    02                                58.0  282.017241
                    03                                76.0  285.381579
                    04                                85.0  290.129412
                    05                               109.0  293.587156
...                                                    ...         ...
ORD                 08                               199.0  242.788945
                    09                               186.0  245.903226
                    10                               149.0  242.194631
                    11                               126.0  244.801587
                    12                               134.0  245.694030


                                std    min    25%    50%    75%    max
Destination Airport Month
ATL                 01     5.077687  279.0  279.0  284.0  291.0  292.0
                    02     2.123316  279.0  281.0  282.5  284.0  284.0
                    03     2.702922  281.0  284.0  284.0  288.0  288.0
                    04     3.511167  284.0  288.0  291.0  293.0  295.0
                    05     2.148259  290.0  291.0  295.0  295.0  296.0
...                             ...    ...    ...    ...    ...    ...
ORD                 08     5.502587  233.0  239.0  244.0  246.0  250.0
                    09     5.558659  236.0  241.0  250.0  250.0  251.0
                    10     8.040168  230.0  235.0  248.0  249.0  249.0
                    11     8.358009  233.0  234.0  248.0  249.0  258.0
                    12     6.260303  236.0  239.0  247.0  250.0  258.0

[108 rows x 16 columns]

## Number of flights per destination airport

In [ ]:
as_flights.groupby("Destination Airport").describe()

                    Flight Number                                          \
                            count         mean         std    min     25%
Destination Airport
ATL                        1119.0   414.245755   82.384170  327.0   334.0
DEN                        1631.0   639.865727   94.980933  199.0   620.0
DFW                        1827.0   516.610837  134.745304  267.0   414.0
JFK                        1327.0    34.435569   79.305470   16.0    16.0
LAS                        2817.0   676.708910   99.736783  211.0   636.0
LAX                        3507.0  1199.821500  144.906292  170.0  1092.0
MCO                        1169.0   366.708298   33.303779  314.0   346.0
MIA                         390.0   295.064103   39.903656  110.0   305.0
ORD                        1821.0   432.641406  118.184682  302.0   352.0

                                            Scheduled elapsed time (Minutes)  \
                        50%     75%     max                            count
Destination Airport
ATL                   376.0   492.0   604.0                           1119.0
DEN                   642.0   682.0  1005.0                           1631.0
DFW                   542.0   586.0   908.0                           1827.0
JFK                    22.0    34.0   746.0                           1327.0
LAS                   688.0   734.0   798.0                           2817.0
LAX                  1224.0  1300.0  1468.0                           3507.0
MCO                   366.0   394.0  1235.0                           1169.0
MIA                   305.0   305.0   314.0                            390.0
ORD                   408.0   486.0  1188.0                           1821.0


                           mean       std    min    25%    50%    75%    max
Destination Airport
ATL                  286.038427  4.790359  275.0  283.0  286.0  289.0  296.0
DEN                  161.249540  2.887400  154.0  159.0  161.0  163.0  168.0
DFW                  231.674330  4.778169  219.0  230.0  233.0  234.0  241.0
JFK                  319.547099  4.729230  309.0  317.0  320.0  324.0  328.0
LAS                  152.027334  2.830868  144.0  150.0  152.0  154.0  157.0
LAX                  167.509267  2.683135  161.0  165.0  168.0  170.0  174.0
MCO                  332.353293  7.925223  315.0  325.0  334.0  338.0  349.0
MIA                  353.815385  6.719252  342.0  348.0  355.0  359.0  364.0
ORD                  244.071938  6.140551  230.0  240.0  245.0  249.0  258.0

#

# Create Sankey Diagram

In [ ]:
import plotly.graph_objects as go

# ---------------------------
# 1) Define Node
# ---------------------------
labels = [
    "Seatac Airport (15608 flights)",      #0

    "January (1078 flights)",              #1
    "February (1013 flights)",             #2
    "March (1215 flights)",                #3
    "April (1241 flights)",                #4
    "May (1371 flights)",                  #5
    "June (1452 flights)",                 #6
    "July (1529 flights)",                 #7
    "August (1512 flights)",               #8
    "September (1434 flights)",            #9
    "October (1300 flights)",              #10
    "November (1188 flights)",             #11
    "December (1275 flights)",             #12

    "ATL (1119 flights)",                  #13
    "LAX (3507 flights)",                  #14
    "DFW (1827 flights)",                  #15
    "DEN (1631 flights)",                  #16
    "ORD (1821 flights)",                  #17
    "JFK (1327 flights)",                  #18
    "MCO (1169 flights)",                  #19
    "LAS (2817 flights)",                  #20
    "MIA (390 flights)",                   #21

]

# ---------------------------
# 2) Define Link
# ---------------------------
source = [
    # Seatac
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

    # Months
    1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,
    1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,
    1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,
    1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,
    1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,
    1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,
    1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,
    1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,
    1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12
]

target = [
    # Seatac to months
    1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,

    # Months to destination airport
    13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13,
    14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14,
    15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
    17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17,
    18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18,
    19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19,
    20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20,
    21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21
]

value = [
    # Seatac to months
    1078, 1013, 1215, 1241, 1371, 1452, 1529, 1512, 1434, 1300, 1188, 1275,

    #Months to destination airport
    67, 58, 76, 85, 109, 120, 124, 122, 108, 90, 78, 82,
    248, 235, 274, 289, 309, 319, 335, 326, 304, 292, 261, 315,
    124, 116, 124, 128, 162, 175, 182, 183, 179, 164, 147, 143,
    106, 98, 113, 110, 139, 168, 186, 180, 165, 129, 115, 122,
    91, 88, 133, 150, 167, 191, 207, 199, 186, 149, 126, 134,
    72, 73, 112, 120, 124, 120, 124, 124, 119, 98, 117, 124,
    113, 110, 122, 104, 93, 90, 93, 93, 89, 87, 82, 93,
    226, 206, 230, 225, 237, 239, 247, 254, 254, 260, 223, 216,
    31, 29, 31, 30, 31, 30, 31, 31, 30, 31, 39, 46
]

# Define a color for each destination airport
airport_colors = {
    13: 'rgba(255, 0, 0, 0.6)',  # ATL Red
    14: 'rgba(0, 0, 255, 0.6)',  # LAX Blue
    15: 'rgba(0, 128, 0, 0.6)',  # DFW Green
    16: 'rgba(128, 0, 128, 0.6)', # DEN Purple
    17: 'rgba(255, 165, 0, 0.6)', # ORD Orange
    18: 'rgba(165, 42, 42, 0.6)', # JFK Brown
    19: 'rgba(255, 192, 203, 0.6)',# MCO Pink
    20: 'rgba(0, 255, 255, 0.6)', # LAS Cyan
    21: 'rgba(255, 0, 255, 0.6)'  # MIA Magenta
}

# Create a list of colors for each link
link_colors = []
# First 12 links are Seatac to Months, set to a neutral color (e.g., grey)
for _ in range(12):
    link_colors.append('rgba(128, 128, 128, 0.6)')

# Remaining links are Month to Destination Airport
for i in range(12, len(target)):
    link_colors.append(airport_colors[target[i]])

# ---------------------------
# 3) Create Sankey
# ---------------------------
fig = go.Figure(
    go.Sankey(
        node = {
            "label": labels,
            "x": [0.01, 0.35, 0.35, 0.35, 0.35, 0.35, 0.35, 0.35, 0.35, 0.35, 0.35, 0.35, 0.35, 0.95, 0.95, 0.95, 0.95, 0.95, 0.95, 0.95, 0.95, 0.95],
            "y": [0.5, 0.08, 0.16, 0.24, 0.32, 0.40, 0.48, 0.56, 0.64, 0.72, 0.8, 0.9, 1, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1],
        },
        link = {
            "source": source,
            "target": target,
            "value": value,
            "color": link_colors
        }

    )
)

fig.update_layout(
    title="Flow of Alaska Airlines flights each month from Seatac airport to destination airport in 2024",
    font=dict(size=12)
)

fig.show()

# Legend
This plot uses color to determine the destination airport for the flights to better visualize the flow from month to destination airport.
* Red for ATL
* Blue for LAX
* Green for DFW
* Purple for DEN
* Yellow for ORD
* Brown for JFK
* Pink for MCO
* Light Blue for LAS
* Magenta for MIA